# Generated by Django 5.2.8 on 2025-12-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория авто',
                'verbose_name_plural': 'Категории авто',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carcategory'),
        ),
        migrations.CreateModel(
            name='CarCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='cars.car')),
            ],
            options={
                'verbose_name': 'Характеристика авто',
                'verbose_name_plural': 'Характеристики авто',
            },
        ),
    ]
