# Generated by Django 5.2.8 on 2025-12-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carcategory_alter_car_options_car_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.carcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='carcharacteristics',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='carcharacteristics',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carcharacteristics',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
    ]
